plugins {
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'edu.sc.seis.launch4j' version '4.0.0'
    id 'application'
}

apply plugin: 'java'
apply plugin: 'eclipse'

application {
   mainClass = 'CreateListingFrontend'
}


eclipse.project.name = 'ManageFLF' 

sourceSets {
	main {
	  java {
		srcDirs = ['src']
	  }
	}
	test {
	  java {
	     srcDirs = ['test']
	  }
    }
}

repositories {
    mavenCentral()
}

javafx {
    modules = [ 'javafx.controls', 'javafx.graphics' ]
}

launch4j {
  headerType="console"
  mainClassName = 'CreateListingFrontend'
  icon = "${projectDir}/icon.ico"
}

dependencies {
    implementation "org.seleniumhq.selenium:selenium-java:4.20.0"
       implementation "org.jsoup:jsoup:1.17.2"
       implementation("org.kohsuke:github-api:1.330")
    implementation("com.google.api-client:google-api-client:2.2.0")
        implementation 'com.google.apis:google-api-services-youtube:v3-rev20251217-2.0.0'
        implementation 'com.restfb:restfb:2025.6.0'
        implementation 'org.openjfx:javafx-swing:21.0.2'
}

test {
    useJUnitPlatform()
}